In [2]:
import pandas as pd

In [ ]:
data = pd.read_csv("California_Fire_Perimeters_(all).csv")
#https://data.ca.gov/dataset/california-fire-perimeters-all

data=data[data["STATE"]=="CA"]
data=data[data["OBJECTIVE"]==1] # wire fire

data

,OBJECTID,YEAR_,STATE,AGENCY,UNIT_ID,FIRE_NAME,INC_NUM,ALARM_DATE,CONT_DATE,CAUSE,...,OBJECTIVE,GIS_ACRES,COMMENTS,COMPLEX_NAME,IRWINID,FIRE_NUM,COMPLEX_ID,DECADES,Shape__Area,Shape__Length
0,1,2023.0,CA,CDF,SKU,WHITWORTH,00004808,2023/06/17 00:00:00+00,2023/06/17 00:00:00+00,5.0,...,1.0,5.729125,NaN,NaN,{7985848C-0AC2-4BA4-8F0E-29F778652E61},NaN,NaN,2020.0,4.140784e+04,1247.166034
1,2,2023.0,CA,LRA,BTU,KAISER,00010225,2023/06/02 00:00:00+00,2023/06/02 00:00:00+00,5.0,...,1.0,13.602380,NaN,NaN,{43EBCC88-B3AC-48EB-8EF5-417FE0939CCF},NaN,NaN,2020.0,9.345588e+04,1285.514550
2,3,2023.0,CA,CDF,AEU,JACKSON,00017640,2023/07/01 00:00:00+00,2023/07/02 00:00:00+00,2.0,...,1.0,27.814460,NaN,NaN,{B64E1355-BF1D-441A-95D0-BC1FBB93483B},NaN,NaN,2020.0,1.830285e+05,2697.587429
3,4,2023.0,CA,CDF,AEU,CARBON,00018821,2023/07/11 00:00:00+00,2023/07/11 00:00:00+00,9.0,...,1.0,58.760230,NaN,NaN,{CB41DB0A-E4B1-489D-A4EA-738F2CD6DB3B},NaN,NaN,2020.0,3.882220e+05,2548.738779
4,5,2023.0,CA,CDF,AEU,LIBERTY,00018876,2023/07/11 00:00:00+00,2023/07/12 00:00:00+00,14.0,...,1.0,70.979000,NaN,NaN,{F83F70A4-07A7-40B8-BD51-10CCC1C30D63},NaN,NaN,2020.0,4.664560e+05,5106.936526
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22256,22257,NaN,CA,CCO,MRN,UKNOWN,NaN,NaN,NaN,14.0,...,1.0,1494.277000,1917-34(Yr Not Report)MarinCo FireChief Garber...,NaN,NaN,NaN,NaN,NaN,9.768233e+06,11458.048312
22257,22258,NaN,CA,CCO,MRN,UKNOWN,NaN,NaN,NaN,14.0,...,1.0,465.534600,1917-34(Yr Not Report)MarinCo FireChief Garber...,NaN,NaN,NaN,NaN,NaN,3.048457e+06,6265.090923
22258,22259,NaN,CA,CCO,MRN,UKNOWN,NaN,NaN,NaN,14.0,...,1.0,2927.242000,1917-34(Yr Not Report)MarinCo FireChief Garber...,NaN,NaN,NaN,NaN,NaN,1.919632e+07,18325.306274
22259,22260,NaN,CA,CCO,MRN,UKNOWN,NaN,NaN,NaN,14.0,...,1.0,62.012680,1917-34(Yr Not Report)MarinCo FireChief Garber...,NaN,NaN,NaN,NaN,NaN,4.048420e+05,2344.122215
22260,22261,NaN,CA,CCO,MRN,UKNOWN,NaN,NaN,NaN,14.0,...,1.0,40.013700,1917-34(Yr Not Report)MarinCo FireChief Garber...,NaN,NaN,NaN,NaN,NaN,2.612574e+05,1855.461908

In [29]:
data2=pd.read_csv("California_County_Boundaries.csv")
data2

,OBJECTID,COUNTY_NAME,COUNTY_ABBREV,COUNTY_NUM,COUNTY_CODE,COUNTY_FIPS,ISLAND,Shape__Area,Shape__Length,GlobalID
0,1,Alameda,ALA,1,1,1,NaN,3.402787e+09,308998.650766,e6f92268-d2dd-4cfb-8b79-5b4b2f07c559
1,2,Alpine,ALP,2,2,3,NaN,3.146939e+09,274888.492411,870479b2-480a-494b-8352-ad60578839c1
2,3,Amador,AMA,3,3,5,NaN,2.562635e+09,361708.438013,4f45b3a6-be10-461c-8945-6b2aaa7119f6
3,4,Butte,BUT,4,4,7,NaN,7.339348e+09,526547.115238,44fba680-aecc-4e04-a499-29d69affbd4a
4,5,Calaveras,CAL,5,5,9,NaN,4.351069e+09,370637.578323,d11ef739-4a1e-414e-bfd1-e7dcd56cd61e
...,...,...,...,...,...,...,...,...,...,...
64,65,Ventura,VEN,56,56,111,Channel Islands,8.750094e+05,11880.900594,86c2171f-d249-45a0-ac0c-40a4e6cb82e2
65,66,Ventura,VEN,56,56,111,Channel Islands,2.595855e+06,14258.527110,71e2d2ad-a83c-4f5d-bc3b-b7ad9b12f57b
66,67,Ventura,VEN,56,56,111,Channel Islands,6.082082e+05,7967.029762,d90412b1-c6af-4437-94d9-48dc3a13a64d
67,68,Los Angeles,LOS,19,19,37,Channel Islands,2.076580e+08,135274.201204,3cb33dc3-e564-4bbf-8528-866600a1f9e4
68,69,Los Angeles,LOS,19,19,37,Channel Islands,2.776172e+08,143353.767327,991044ae-cbc3-43b8-898a-702c5315293c

In [1]:
import geopandas as gpd

gdf = gpd.read_file("POSTFIRE_MASTER_DATA_SHARE.geojson", engine="fiona")
#from https://www.kaggle.com/datasets/vijayveersingh/the-california-wildfire-data/data


#fire23_1 from cal fire original dataset2 
print(gdf.head())

ModuleNotFoundError: No module named 'geopandas'